# Generated by Django 2.2.28 on 2023-02-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_petowner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="price",
        ),
        migrations.AddField(
            model_name="pet",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
