# Generated by Django 2.2.28 on 2023-02-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230224_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetOwner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
