# Generated by Django 2.2.28 on 2024-05-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230224_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
