# Generated by Django 2.2.28 on 2024-05-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230131_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='was_active_today',
        ),
    ]
